/**
 * Clip 02 — UC-07 The daily arrival brief.
 *
 * Three beats:
 *   1) TEST CASE  — scene card.
 *   2) SCREEN FLOW — open the brief; a banner walks the screen: the arrival
 *                    stats, the guest flagged for attention with their real
 *                    issue, and the ready-to-say greeting + preference callouts.
 *   3) LIVE TEST  — assert the brief has the ranked arrivals + the attention flag.
 */
import { test, expect } from '@playwright/test';
import {
  showSceneCard, showStepBanner, showStoryboard, showVerdict, clearBanner, clearOverlay,
  scrollTopToBottom, signInAndGetToken, liveCall, pause,
  WEB_BASE, DEMO_PROPERTY_ID,
} from './clip-helpers';

test('clip-02-brief', async ({ page, playwright }) => {
  test.setTimeout(120_000);
  const api = await playwright.request.newContext({ ignoreHTTPSErrors: true });

  await showSceneCard(page, {
    step: 'TEST CASE \u00b7 UC-07 \u00b7 THE MORNING BRIEF',
    given: 'Several guests are arriving today, each with their own history and preferences',
    when: 'The front desk opens the daily brief',
    then: 'Each arrival is ranked with a ready-to-say greeting, key preferences, and any recent issue flagged',
    durationMs: 6_000,
  });
  await clearOverlay(page);

  const token = await signInAndGetToken(page, api);

  // Today's brief is produced on demand (not auto-created); generate it live
  // so the screen has a real, fresh brief to show.
  await liveCall(api, token, 'POST', '/v1/briefs/generate', {
    propertyId: DEMO_PROPERTY_ID,
    force: true,
  });

  // ---- SCREEN FLOW storyboard (its own beat, before the live brief) -------
  await showStoryboard(page, {
    title: 'SCREEN FLOW \u00b7 THE MORNING BRIEF',
    steps: [
      { screen: 'ARRIVALS', blank: '[today\u2019s bookings]', filled: 'each guest + history', action: 'Rank', produces: 'GET /briefs/today => arrivals ordered by who needs care' },
      { screen: 'ATTENTION', blank: '[unranked]', filled: 'recent issues surfaced', action: 'Flag', produces: 'the guest with an open issue is ranked first' },
      { screen: 'SAY THIS', blank: '[no script]', filled: 'top preferences', action: 'Draft', produces: 'ERNIE 4.5 => a ready greeting per card' },
    ],
    outcome: 'The shift\u2019s shape in one screen \u2014 who\u2019s coming, who needs care, what to say',
    durationMs: 9_000,
  });
  await clearOverlay(page);

  await page.goto(`${WEB_BASE}/`);
  await pause(page, 1_400);

  await showStepBanner(page, {
    stepLabel: 'THE BRIEF \u00b7 TODAY AT A GLANCE',
    headline: 'Arrivals today, VIPs, and how many need attention \u2014 the shift\u2019s shape in one line.',
    detail: 'Generated by ERNIE 4.5 from each guest\u2019s history and preferences.',
  });
  await pause(page, 2_600);

  await showStepBanner(page, {
    stepLabel: 'THE BRIEF \u00b7 FLAGGED FOR ATTENTION',
    headline: 'The guest who needs care is ranked first, with their real recent issue shown.',
    detail: 'No surprises at the desk \u2014 the agent already knows before the guest arrives.',
  });
  await scrollTopToBottom(page, 3_200);
  await pause(page, 800);

  await showStepBanner(page, {
    stepLabel: 'THE BRIEF \u00b7 \u201cSAY THIS\u201d',
    headline: 'Each card gives a ready greeting and the preferences to mention.',
    detail: 'The agent can sound like they remember the guest \u2014 because the system does.',
  });
  await pause(page, 2_400);
  await clearBanner(page);

  const brief = await liveCall(api, token, 'GET', `/v1/properties/${DEMO_PROPERTY_ID}/briefs/today`);
  const b = brief.body as { brief?: { total_arrivals?: number; attention_count?: number }; items?: unknown[] };
  const arrivals = b?.brief?.total_arrivals ?? 0;
  const attention = b?.brief?.attention_count ?? 0;
  const items = Array.isArray(b?.items) ? b.items.length : 0;

  await showVerdict(page, {
    title: 'UC-07 \u00b7 DAILY BRIEF',
    request: 'GET /v1/properties/{id}/briefs/today',
    assertions: [
      { label: 'Brief loaded', expected: '200', actual: String(brief.status), pass: brief.status === 200 },
      { label: 'Ranked arrivals', expected: '3', actual: String(arrivals), pass: arrivals === 3 },
      { label: 'Cards rendered', expected: '3', actual: String(items), pass: items === 3 },
      { label: 'Flagged for attention', expected: '\u2265 1', actual: String(attention), pass: attention >= 1 },
    ],
  });
  await pause(page, 4_800);
  await clearOverlay(page);

  // Hard assertions \u2014 a false verdict row fails the test.
  expect(brief.status, 'brief must load').toBe(200);
  expect(arrivals, 'three ranked arrivals expected').toBe(3);
  expect(items, 'three brief cards expected').toBe(3);
  expect(attention, 'at least one guest flagged for attention').toBeGreaterThanOrEqual(1);
});
